version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_kandinskiy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - 27020:27017
  redis:
    image: redis:latest
    container_name: redis_kandinskiy
    ports:
      - 6379:6379
